-- ==========================================
-- SIIT - SISTEMA DE TICKETS (SUNAFIL)
-- SCRIPT DE INICIALIZACIÓN DE DATOS (DML ORACLE 19c)
-- ==========================================

-- Insertar ROLES
INSERT INTO ROLES (NOMBRE_ROL) VALUES ('ADMIN');
INSERT INTO ROLES (NOMBRE_ROL) VALUES ('ESPECIALISTA');
INSERT INTO ROLES (NOMBRE_ROL) VALUES ('INSPECTOR');
INSERT INTO ROLES (NOMBRE_ROL) VALUES ('SUPERVISOR');
INSERT INTO ROLES (NOMBRE_ROL) VALUES ('SIFS');
INSERT INTO ROLES (NOMBRE_ROL) VALUES ('SIFN');
INSERT INTO ROLES (NOMBRE_ROL) VALUES ('SISA');

-- Insertar INTENDENCIAS
INSERT INTO INTENDENCIAS (COD_IRE, NOMBRE_IRE) VALUES ('DINI', 'Dirección de Inteligencia Inspectiva');
INSERT INTO INTENDENCIAS (COD_IRE, NOMBRE_IRE) VALUES ('APURIMAC', 'Intendencia Regional de Apurímac');
INSERT INTO INTENDENCIAS (COD_IRE, NOMBRE_IRE) VALUES ('LIMA_METRO', 'Intendencia de Lima Metropolitana');
INSERT INTO INTENDENCIAS (COD_IRE, NOMBRE_IRE) VALUES ('CALLAO', 'Intendencia Regional del Callao');

-- Insertar USUARIOS (Contraseña por defecto encriptada con BCrypt: "Sunafil2026!")
-- admin: $2a$10$mB/q8N/7XhXyXvR.V0.JjODLszq5H.4.Q17D0t797Y.GjW71pZ06W
INSERT INTO USUARIOS (USERNAME, PASSWORD, EMAIL, ID_ROL, COD_IRE, ESPECIALISTA_NUM, DEBE_CAMBIAR_PASSWORD, ACTIVO)
VALUES (
    'admin', 
    '$2a$10$mB/q8N/7XhXyXvR.V0.JjODLszq5H.4.Q17D0t797Y.GjW71pZ06W', 
    'admin@sunafil.gob.pe', 
    (SELECT ID_ROL FROM ROLES WHERE NOMBRE_ROL = 'ADMIN'), 
    NULL, 
    NULL, 
    0, 
    1
);

INSERT INTO USUARIOS (USERNAME, PASSWORD, EMAIL, ID_ROL, COD_IRE, ESPECIALISTA_NUM, DEBE_CAMBIAR_PASSWORD, ACTIVO)
VALUES (
    'especialista1', 
    '$2a$10$mB/q8N/7XhXyXvR.V0.JjODLszq5H.4.Q17D0t797Y.GjW71pZ06W', 
    'especialista1@sunafil.gob.pe', 
    (SELECT ID_ROL FROM ROLES WHERE NOMBRE_ROL = 'ESPECIALISTA'), 
    NULL, 
    1, 
    0, 
    1
);

INSERT INTO USUARIOS (USERNAME, PASSWORD, EMAIL, ID_ROL, COD_IRE, ESPECIALISTA_NUM, DEBE_CAMBIAR_PASSWORD, ACTIVO)
VALUES (
    'percy', 
    '$2a$10$mB/q8N/7XhXyXvR.V0.JjODLszq5H.4.Q17D0t797Y.GjW71pZ06W', 
    'percy@sunafil.gob.pe', 
    (SELECT ID_ROL FROM ROLES WHERE NOMBRE_ROL = 'INSPECTOR'), 
    'APURIMAC', 
    NULL, 
    0, 
    1
);

-- Insertar INCIDENCIAS
INSERT INTO INCIDENCIAS (NOMBRE_INCIDENCIA, ESPECIALISTA_NUM)
VALUES ('Corrección de Expediente de Inspección', 1);

INSERT INTO INCIDENCIAS (NOMBRE_INCIDENCIA, ESPECIALISTA_NUM)
VALUES ('Reinicio de Contraseña del Sistema SIIT', 1);

INSERT INTO INCIDENCIAS (NOMBRE_INCIDENCIA, ESPECIALISTA_NUM)
VALUES ('Problemas de Acceso a Casilla Electrónica', 1);

-- Inicializar secuencias para intendencias
INSERT INTO TICKET_SEQUENCES (COD_IRE, CURRENT_VALUE) VALUES ('APURIMAC', 0);
INSERT INTO TICKET_SEQUENCES (COD_IRE, CURRENT_VALUE) VALUES ('LIMA_METRO', 0);
INSERT INTO TICKET_SEQUENCES (COD_IRE, CURRENT_VALUE) VALUES ('DINI', 0);
INSERT INTO TICKET_SEQUENCES (COD_IRE, CURRENT_VALUE) VALUES ('CALLAO', 0);
